export const countryCode = {
    'India' : 'IND',
    'Portugal' : 'PRT',
    'Ukraine' : 'UKR',
    'Poland' : 'POL',
    'Morocco' : 'MAR',
    'Nigeria' : 'NGA',
    'Afghanistan' : 'AFG',
    'Lebanon' : 'LBN',
    'Syria' : 'SYR',
    'Turkey' : 'TUR',
    'China' : 'CHN',
    'Serbia' : 'SRB',
    'Philippines' : 'PHL',
    'Sri Lanka' : 'LKA',
    'Ireland' : 'IRL',
    'Tunisia' : 'TUN',
    'Jordan' : 'JOR',
    'France' : 'FRA',
    'Brazil' : 'BRA',
    'Colombia' : 'COL',
    'Mexico' : 'MEX',
    'Germany' : 'DEU'    
}