name: React CI/CD

on:
#   pull_request:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: irccreactwebappdev
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL_DEV }}
  AZURE_RESOURCE_GROUP: irccreactresourcegroupdev
  AZURE_APP_PLAN: irccreactserviceplandev
  WEBHOOK_NAME: reactwebhookdev

jobs:
  local-build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install
    
    - name: Test
      run: npm test

    - name: Build
      run: npm run build
  
  docker_build_and_deploy:
    needs: local-build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Authenticate using a Service Principal
      uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_SP_DEV }}
      
        
    - uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL_DEV}}
        username: ${{ secrets.REGISTRY_USERNAME_DEV }}
        password: ${{ secrets.REGISTRY_PASSWORD_DEV }}

    - name: Build and push the image tagged with the git commit hash
      run: |
        docker build . -t ${{ env.CONTAINER_REGISTRY }}/reactapp2:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/reactapp2:${{ github.sha }} 
        
# Uncomment the below action snippet if the Web app credentials are not updated as web app settings
    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        app-settings-json: |
          [
              {
                  "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                  "value": "${{ secrets.REGISTRY_PASSWORD_DEV }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_URL",
                  "value": "https://${{ env.CONTAINER_REGISTRY }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                  "value": "${{ secrets.REGISTRY_USERNAME_DEV  }}",
                  "slotSetting": false
              },
              {
                  "name": "DOCKER_ENABLE_CI",
                  "value": "true"
              }
          ]
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/reactapp2:${{ github.sha }}

    # 
    - name: Create Container Registry Webhook to WebApp
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          ci_cd_url=$(az webapp deployment container config --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP}} --enable-cd true --query CI_CD_URL --output tsv)
          az acr webhook create --name ${{ env.WEBHOOK_NAME }} --registry ${{ env.CONTAINER_REGISTRY}} --resource-group ${{ env.AZURE_RESOURCE_GROUP}} --actions push --uri $ci_cd_url --scope reactapp2:${{ github.sha }}
